#include "stm32f103x6.h"


void Init_Ports(){
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN;

    //port 0 config
    GPIOA->CRL &= ~(GPIO_CRL_MODE0_Msk | GPIO_CRL_CNF0_Msk);
    GPIOA->CRL |= GPIO_CRL_CNF0_1;
    GPIOA->BSRR = GPIO_BSRR_BS0;

    //port 1 config
    GPIOA->CRL &= ~(GPIO_CRL_MODE1_Msk | GPIO_CRL_CNF1_Msk);
    GPIOA->CRL |= GPIO_CRL_CNF1_1;
    GPIOA->BSRR = GPIO_BSRR_BS1;

    GPIOA->CRL &= ~(GPIO_CRL_MODE7_Msk | GPIO_CRL_CNF7_Msk);
    GPIOA->CRL |= GPIO_CRL_CNF7_1;
    GPIOA->BSRR = GPIO_BSRR_BR7;

    GPIOB->CRL &= ~(GPIO_CRL_CNF0_Msk | GPIO_CRL_MODE0_Msk);
    GPIOB->CRL |= GPIO_CRL_MODE0_1 | GPIO_CRL_MODE0_0;

    GPIOB->CRL &= ~(GPIO_CRL_CNF4_Msk | GPIO_CRL_MODE4_Msk);
    GPIOB->CRL |= GPIO_CRL_MODE4_1 | GPIO_CRL_MODE4_0;

    GPIOB->CRL &= ~(GPIO_CRL_CNF5_Msk | GPIO_CRL_MODE5_Msk);
    GPIOB->CRL |= GPIO_CRL_MODE5_1 | GPIO_CRL_MODE5_0;

    GPIOB->CRL &= ~(GPIO_CRL_CNF6_Msk | GPIO_CRL_MODE6_Msk);
    GPIOB->CRL |= GPIO_CRL_MODE6_1 | GPIO_CRL_MODE6_0;

    GPIOB->CRL &= ~(GPIO_CRL_CNF7_Msk | GPIO_CRL_MODE7_Msk);
    GPIOB->CRL |= GPIO_CRL_MODE7_1 | GPIO_CRL_MODE7_0;

    AFIO->EXTICR[0] &= ~AFIO_EXTICR1_EXTI0;
    EXTI->IMR |= EXTI_IMR_MR0;
    EXTI->FTSR |= EXTI_FTSR_TR0;
    EXTI->RTSR |= EXTI_RTSR_TR0;

    AFIO->EXTICR[0] &= ~AFIO_EXTICR1_EXTI1;
    EXTI->IMR |= EXTI_IMR_MR1;
    EXTI->FTSR |= EXTI_FTSR_TR1;
    EXTI->RTSR |= EXTI_RTSR_TR1;

    AFIO->EXTICR[1] &= ~AFIO_EXTICR2_EXTI7;
    EXTI->IMR |= EXTI_IMR_MR7;
    EXTI->RTSR |= EXTI_RTSR_TR7;
    EXTI->FTSR |= EXTI_FTSR_TR7;
}


void Init_Timer3(){

    RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
    RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;

    TIM3->CR1 &= ~(TIM_CR1_UDIS_Msk | TIM_CR1_URS_Msk | TIM_CR1_OPM_Msk | TIM_CR1_DIR_Msk | TIM_CR1_CMS_Msk | TIM_CR1_CKD_Msk);
    TIM3->CR1 |= TIM_CR1_ARPE;
    TIM3->DIER |= TIM_DIER_UIE;

    TIM3->PSC = 8 - 1;
    TIM3->ARR = 1000 - 1;

    NVIC_EnableIRQ(TIM3_IRQn);
}

void Init_SysTick(){
    SysTick->LOAD = 400000 - 1;
    SysTick->VAL  = 0;

    SysTick->CTRL =
          SysTick_CTRL_CLKSOURCE_Msk | 
          SysTick_CTRL_TICKINT_Msk   |
          SysTick_CTRL_ENABLE_Msk;
}